# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    cache_lite:
        class:  DashboardBundle\Services\CacheLiteService
        arguments: ['%cache_options%']
    memcache_rep:
        class:  DashboardBundle\Repository\MemcacheMessageRepository
        arguments: ['@cache_lite', '@session']
